(function() {
    // 清單中所有變數名稱
    const varsToClear = [
        //"Bedroom_Study_phase",
        "CE_Toggle",
        "CE_YL_leftui_enable",
        "CE_milk_max",
        "CE_milk_volume",
        "CE_semen_max",
        "CE_semen_volume",
        "CE_tattoo",
        "CE_tattoo_index",
        //舊的 敵人狀態顯示變量（之後會棄用）
        "HP_AP_display_swich",               
        "bigest_wardrobe_fix",
        "bigest_wardrobe_swich",
        "black_store_FIX_MAX",
        "black_store_FIX_MIN",
        "black_storeswich",
        "brothel_basement_price",
        "brothel_basement_price_FIX",
        "brothel_basement_swich",
        "cccheat",
        "cccheat_display",
        "cccheat_name",
        "cccheat_name_display",
        "ccpassagecount",
        "ccplot",
        //舊版傷害加倍變數⬇️
        "damage",
        "damage_oringinal",
        //舊版傷害加倍變數 End
        "dance_reward_swich",
        "dancetip_FIX",        
        "fromIndex",
        "history_exam",
        "incompletePregnancyDisable",
        "index_max",
        "index_min",        
        "milk_releasedFIX",
        "milk_releasedFIX_MAX",
        "milk_releasedFIX_MIN",
        "milk_releasedswich",
        //舊的疼痛衰減變數⬇️
        "painfix", 
        "painfixset",
        //舊版疼痛衰減變數 End        
        "semen_releasedFIX",
        "semen_releasedswich",        
        "stall_cost_FIX",
        "study_hard",
        "swich",
        "swich_auto_clothes_Warmth",
        "swich_bccmeditor",
        "swich_teleportation",
        "swich_yanling",
        "teleportation",
        "teleportation_name",
        "toIndex",
        "yanling_ui_hide",
        "CE_SFflag",
        "CE_forceAttendSchool",
        // 新增 CE 控制面板變數
        "CE_painCheat",
        "CE_painMultiplier",
        "CE_painNegativeMultiplier",
        "CE_traumaCheat",
        "CE_traumaMultiplier",
        "CE_traumaNegativeMultiplier",
        "CE_controlCheat",
        "CE_controlMultiplier",
        "CE_controlNegativeMultiplier",
        "CE_stressCheat",
        "CE_stressMultiplier",
        "CE_stressNegativeMultiplier",
        "CE_sensCheat",
        "CE_sensMultiplier",
        "CE_sensNegativeMultiplier",
        "CE_arousalCheat",
        "CE_arousalMultiplier",
        "CE_arousalNegativeMultiplier",
        "CE_tiredCheat",
        "CE_tiredMultiplier",
        "CE_tiredNegativeMultiplier",
        "CE_skillCheat",
        "CE_skillMultiplier",
        "CE_timePassMultiplier",
        "CE_timeMultiplier",
        "CE_violenceEnabled",
        "CE_violenceMultiplier",
        "CE_damageEnabled",
        "CE_damageMultiplier",
        "CE_forceEnableCheat",
        "CE_sideBarIconEnable",
        "CE_featBypass",
        "CE_purityControl",
        "CE_purityMax",
        "CE_purityAddMultiplier",
        "CE_puritySubMultiplier",
        "CE_parasiteControl",
        "CE_parasiteMaxAnus",
        "CE_parasiteMaxVagina",
        "CE_parasiteUnlimited",
        "CE_parasiteMultiplierEnable",
        "CE_parasiteMultiplier",
        "CE_EnemyStateEnable",
        "CE_hideUiBarToggleEnable",
        "CE_autoRepairClothesEnabled",
        "CE_autoRepairClothesRatio",
        "CE_autoRepairClothesLockSlots",
        "CE_nectarKeeperEnabled",
        "CE_LastTab",
        "CE_TabHidden",
        "CE_TabFavorite",
        
        // ===========================
        // CE 轉化每日增加模組變數
        // ===========================
        "CE_angelBuildDailyGainEnabled",
        "CE_angelBuildDailyGainAmount",
        "CE_fallenangelBuildDailyGainEnabled",
        "CE_fallenangelBuildDailyGainAmount",
        "CE_demonBuildDailyGainEnabled",
        "CE_demonBuildDailyGainAmount",
        "CE_wolfBuildDailyGainEnabled",
        "CE_wolfBuildDailyGainAmount",
        "CE_catBuildDailyGainEnabled",
        "CE_catBuildDailyGainAmount",
        "CE_cowBuildDailyGainEnabled",
        "CE_cowBuildDailyGainAmount",
        "CE_birdBuildDailyGainEnabled",
        "CE_birdBuildDailyGainAmount",
        "CE_foxBuildDailyGainEnabled",
        "CE_foxBuildDailyGainAmount",
        "CE_lockOxygenEnabled"
    ];

    // 封裝成全局函數
    function clearCEVars () {
        varsToClear.forEach(v => {
            State.variables[v] = undefined; // 清空變數
        });
        console.log("[Cheat Extended] 🔧已清除 CE 相關變數清單");
    };
    window.clearCEVars = clearCEVars;
})();